#!/usr/bin/env python3
"""Markdown link audit: checks all relative links resolve.

Includes GitHub-style heading anchor detection for Chinese and English headings.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT_DIR = os.path.join(ROOT, "audit_reports")
os.makedirs(REPORT_DIR, exist_ok=True)

LINK_RE = re.compile(r'\[([^\]]*)\]\(([^)]+)\)')

def github_slugify(text):
    """Convert markdown heading text to GitHub-style anchor ID.

    GitHub heading ID algorithm:
    1. Remove backtick delimiters, keep code span content
    2. Remove punctuation chars individually
       (< and > are individual chars, NOT HTML tags - so Vec<T> becomes VecT)
    3. Lowercase
    4. Replace EACH space with dash individually (not whitespace grouping)
    5. Strip leading/trailing dashes
    """
    # Remove backtick delimiters but KEEP code span content
    text = text.replace('`', '')  # backtick `
    # Remove punctuation characters individually
    # CRITICAL: < and > removed as individual chars, preserving generics like Vec<T> -> VecT
    text = re.sub(
        r'[.,()?!:;\"' + "'" + r'/\\\[\]{}*+=~@#$%^&<>'
        r'！（），．：；？'  # full-width ! ( ) , . : ; ?
        r'、。～‘’“”…'    # 、 。 ' " " ...
        r'—–－]',  # em dash, en dash, full-width dash
        '', text)
    # Lowercase
    text = text.lower()
    # Strip leading/trailing whitespace
    text = text.strip()
    # Replace EACH space char with dash individually (not grouping!)
    # "struct  impl" (two spaces) becomes "struct--impl"
    text = text.replace(' ', '-')
    text = text.replace('\t', '-').replace('\n', '-')
    # Strip leading/trailing dashes
    text = text.strip('-')
    # Collapse 3+ consecutive dashes to max 2
    text = re.sub(r'-{3,}', '--', text)
    return text

def extract_heading_anchors(file_content):
    """Extract all valid heading anchors from markdown content.
    Returns set of anchor IDs that would be generated by GitHub renderer.
    """
    anchors = set()
    # Match ATX headings: ## heading text
    heading_re = re.compile(r'^#{1,6}\s+(.+?)(?:\s*\{#[^}]+\})?\s*$', re.MULTILINE)
    for m in heading_re.finditer(file_content):
        heading_text = m.group(1).strip()
        # GitHub slugifies heading text
        slug = github_slugify(heading_text)
        if slug:
            anchors.add(slug)
        # Also add the raw text (some renderers keep non-ASCII as-is)
        raw = heading_text.strip()
        if raw:
            anchors.add(raw)
    return anchors

def check_anchor_in_content(file_content, anchor):
    """Check if an anchor reference would resolve in this markdown content."""
    if not anchor:
        return True  # No anchor to check

    # Check heading anchors
    anchors = extract_heading_anchors(file_content)
    if anchor in anchors:
        return True

    # Check for explicit HTML anchors
    qt = r'["' + "'" + r'"]'
    html_anchor_re = re.compile(
        r'<a\s+[^>]*?(?:id|name)\s*=\s*' + qt + re.escape(anchor) + qt
    )
    if html_anchor_re.search(file_content):
        return True

    # Check for explicit id attributes (on any element)
    id_re = re.compile(
        r'\bid\s*=\s*' + qt + re.escape(anchor) + qt
    )
    if id_re.search(file_content):
        return True

    # Check for {#custom-anchor} syntax
    custom_anchor_re = re.compile(
        r'\{#' + re.escape(anchor) + r'\}'
    )
    if custom_anchor_re.search(file_content):
        return True

    return False


broken = []
external = []
checked = 0
anchor_only_checked = 0

for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d not in ("target", ".git", "audit_reports", "__pycache__")]
    for fn in filenames:
        if not fn.endswith(".md"):
            continue
        full_path = os.path.join(dirpath, fn)
        rel_file = os.path.relpath(full_path, ROOT)
        file_dir = os.path.dirname(full_path)

        try:
            with open(full_path, "r", encoding="utf-8") as fh:
                content = fh.read()
                lines = content.split("\n")
        except Exception as e:
            broken.append({"file": rel_file, "line": 1, "link": "", "target": "", "reason": f"Read error: {e}", "fix": ""})
            continue

        for lineno, line in enumerate(lines, 1):
            for m in LINK_RE.finditer(line):
                text = m.group(1)
                link = m.group(2)
                checked += 1

                # Skip external URLs
                if link.startswith(("http://", "https://", "mailto:")):
                    external.append({"file": rel_file, "line": lineno, "text": text, "link": link})
                    continue

                # Split link into file part and anchor part
                if "#" in link:
                    target_file = link.split("#")[0]
                    anchor = "#".join(link.split("#")[1:])
                else:
                    target_file = link
                    anchor = ""

                # Anchor-only link (within same file)
                if not target_file:
                    anchor_only_checked += 1
                    if anchor and not check_anchor_in_content(content, anchor):
                        broken.append({
                            "file": rel_file, "line": lineno, "text": text, "link": link,
                            "target": "(same file) anchor #" + anchor,
                            "reason": "Anchor not found",
                            "fix": "Check heading text matches anchor"
                        })
                    continue

                # File link
                resolved = os.path.normpath(os.path.join(file_dir, target_file))
                rel_resolved = os.path.relpath(resolved, ROOT)

                if not os.path.exists(resolved):
                    # Try to find a similar file
                    base = os.path.basename(target_file)
                    candidates = []
                    for dp, _, fs in os.walk(ROOT):
                        dp_rel = os.path.relpath(dp, ROOT)
                        if any(s in dp_rel for s in ["target", ".git", "audit_reports"]):
                            continue
                        for candidate in fs:
                            if candidate == base:
                                candidates.append(os.path.join(dp_rel, candidate))
                    fix_suggestion = " -> perhaps: " + ", ".join(candidates[:3]) if candidates else ""

                    broken.append({
                        "file": rel_file, "line": lineno, "text": text, "link": link,
                        "target": rel_resolved,
                        "reason": "File does not exist",
                        "fix": fix_suggestion
                    })
                elif anchor:
                    # File exists, check anchor
                    try:
                        with open(resolved, "r", encoding="utf-8") as tf:
                            target_content = tf.read()
                    except Exception:
                        broken.append({
                            "file": rel_file, "line": lineno, "text": text, "link": link,
                            "target": rel_resolved + "#" + anchor,
                            "reason": "Cannot read target file",
                            "fix": ""
                        })
                        continue

                    if not check_anchor_in_content(target_content, anchor):
                        broken.append({
                            "file": rel_file, "line": lineno, "text": text, "link": link,
                            "target": rel_resolved + "#" + anchor,
                            "reason": "Anchor not found in target file",
                            "fix": "Check if heading exists in target file"
                        })

# Generate report
report_path = os.path.join(REPORT_DIR, "markdown_links_report.md")
with open(report_path, "w", encoding="utf-8") as fh:
    fh.write("# Markdown Link Audit Report\n\n")
    fh.write(f"**Total links checked**: {checked}\n")
    fh.write(f"**Anchor-only links**: {anchor_only_checked}\n")
    fh.write(f"**Broken links**: {len(broken)}\n")
    fh.write(f"**External links** (not verified): {len(external)}\n\n")

    if broken:
        fh.write("## Broken Links\n\n")
        fh.write("| Source File | Line | Link Target | Issue | Suggested Fix |\n")
        fh.write("|-------------|------|-------------|-------|---------------|\n")
        for b in broken:
            fh.write(f"| `{b['file']}` | {b['line']} | `{b['link']}` | {b['reason']} | {b.get('fix', '')} |\n")

        fh.write("\n## Broken Link Detail\n\n")
        for b in broken:
            fh.write(f"### {b['file']}:{b['line']}\n\n")
            fh.write(f"- **Link text**: {b['text']}\n")
            fh.write(f"- **Link target**: `{b['link']}`\n")
            fh.write(f"- **Resolved to**: `{b['target']}`\n")
            fh.write(f"- **Issue**: {b['reason']}\n")
            if b.get('fix'):
                fh.write(f"- **Suggested fix**: {b['fix']}\n")
            fh.write("\n")
    else:
        fh.write("## All Links Valid\n\n")
        fh.write("No broken relative links found.\n\n")

    if external:
        from collections import Counter
        from urllib.parse import urlparse
        domains = Counter()
        for e in external:
            try:
                domain = urlparse(e["link"]).netloc
                domains[domain] += 1
            except Exception:
                domains["(parse error)"] += 1
        fh.write(f"## External URLs ({len(external)})\n\n")
        fh.write("| Domain | Count |\n|--------|------|\n")
        for domain, count in domains.most_common(20):
            fh.write(f"| {domain} | {count} |\n")
        fh.write("\n<details>\n<summary>All external links</summary>\n\n")
        for e in external:
            fh.write(f"- `{e['file']}:{e['line']}` -> [{e['text']}]({e['link']})\n")
        fh.write("\n</details>\n")

    total_broken = len(broken)
    if total_broken > 0:
        fh.write(f"\n**FAIL**: {total_broken} broken links found.\n")
    else:
        fh.write(f"\n**PASS**: All relative links valid.\n")

print(f"Markdown link audit report written to {report_path}")
print(f"Checked={checked}, Broken={len(broken)}, External={len(external)}")

sys.exit(1 if broken else 0)
